### PR TITLE
Draw Fermi level in the panels of bands and DOS

### PR DESCRIPTION
**Pull request by yw-fang**
Hi, Dr. Ganose( @utf ) and Dr. Jakson @ajjackson 

Firstly, Thank you very much for your code.

Secondly, I noticed that the Fermi level is only drawn if the Fermi energy is not shifted to zero. However, I think it's better to show it clearly in both bands and DOS panels no matter shift or not.
Showing the Fermi level clearly is important for all the materials (although it's only my personal opinion). For example, in insulators, it can easily help tell the direct bandgap or indirect bandgap. More importantly, for the topological semimetals and topological insulators that show singular points around the Fermi level, this line can help to know whether they are exactly located on the Fermi level. Hence, I made minor revisions to show the Fermi level lines on bands and DOS. Because in the dos_plotter.py, there is a possibility that the legend is on top of the Fermi level, so I used a very light black (alpha = 0.3) to show the Fermi level. In addition, the 'dashed' style has been used in bands plotter (for the spin down channel), hence I used the 'dashdot' style to show the Fermi level. 
This is just a personal opinion, but you may have a consideration of it. Thank you very much!

FYI: A sample figure with the Fermi level lines shown
image

### CODE REVIEW

**Comment by ajjackson** [comment]
Hi, thank you for your interest in Sumo and your suggestion to display the Fermi energy.

I have discussed this with @scanlond . We prefer not to indicate the Fermi level by default because in a semiconductor or insulator DOS calculation the Fermi level will be, at best, at an "ideal" mid-gap level. In practice it can be quite sensitive to the calculation convergence, and I would be especially suspicious of Fermi energies from non-self-consistent band structure calculations. In any case there is actually a bigger problem: a single DFT calculation will not be representative of a real system, in which defects will determine the actual Fermi level. We use the VBM as a reference instead because it is unambiguous and allows the fundamental bandgap to be seen more easily.

That being said, it is a popular convention to zero the energy scale at E_F, and such a feature might be useful for making comparisons to other figures. I think it is redundant to align the energy scale to the VBM _and_ indicate the Fermi energy; it makes more sense to independently offer options to 

1. align the energy scale to the calculation Fermi energy (or some other value, such as a separately calculated [self-consistent Fermi energy](https://doi.org/10.1016/j.cpc.2019.06.017) )
2. draw a horizontal line at zero

For the purposes of clarifying an indirect bandgap, option 2 will be sufficient without making a potentially-misleading energy alignment. If a line at the Fermi energy really is desired, it can be done at zero as in your example by selecting both options. Other alignments could be useful if employed responsibly. 

If we do add a horizontal line I would prefer if the implementation is shared with _phonon-bandplot_:

```python
            ax.axhline(0, color=rcParams['grid.color'], linestyle='--',
                       dashes=dashes,
                       zorder=0,
                       linewidth=rcParams['ytick.major.width'])
```
This implementation is intended to follow alternate appearance styles sensibly. (Actually it seems to be broken at the moment, but I'm looking into it.)

We would also need to consider the interaction with the existing `--no-shift` option to _dosplot_ .

**Comment by ajjackson** [comment]
Hi, thank you for your interest in Sumo and your suggestion to display the Fermi energy.

I have discussed this with @scanlond . We prefer not to indicate the Fermi level by default because in a semiconductor or insulator DOS calculation the Fermi level will be, at best, at an "ideal" mid-gap level. In practice it can be quite sensitive to the calculation convergence, and I would be especially suspicious of Fermi energies from non-self-consistent band structure calculations. In any case there is actually a bigger problem: a single DFT calculation will not be representative of a real system, in which defects will determine the actual Fermi level. We use the VBM as a reference instead because it is unambiguous and allows the fundamental bandgap to be seen more easily.

That being said, it is a popular convention to zero the energy scale at E_F, and such a feature might be useful for making comparisons to other figures. I think it is redundant to align the energy scale to the VBM _and_ indicate the Fermi energy; it makes more sense to independently offer options to 

1. align the energy scale to the calculation Fermi energy (or some other value, such as a separately calculated [self-consistent Fermi energy](https://doi.org/10.1016/j.cpc.2019.06.017) )
2. draw a horizontal line at zero

For the purposes of clarifying an indirect bandgap, option 2 will be sufficient without making a potentially-misleading energy alignment. If a line at the Fermi energy really is desired, it can be done at zero as in your example by selecting both options. Other alignments could be useful if employed responsibly. 

If we do add a horizontal line I would prefer if the implementation is shared with _phonon-bandplot_:

```python
            ax.axhline(0, color=rcParams['grid.color'], linestyle='--',
                       dashes=dashes,
                       zorder=0,
                       linewidth=rcParams['ytick.major.width'])
```
This implementation is intended to follow alternate appearance styles sensibly. (Actually it seems to be broken at the moment, but I'm looking into it.)

We would also need to consider the interaction with the existing `--no-shift` option to _dosplot_ .

**Comment by yw-fang** [comment]
@ajjackson Thanks very much for the quick reply to explain the background logic.

> In any case there is actually a bigger problem: a single DFT calculation will not be representative of a real system, in which defects will determine the actual Fermi level. We use the VBM as a reference instead because it is unambiguous and allows the fundamental bandgap to be seen more easily.

From this point of view of the defect, I agree with your opinions. It's better not to add a line in such cases. So, this Fermi level line is better to be an independent option that can be controlled by the users themselves.

As for the accuracy of Fermi energy from NSCF calculations, I also noted this problem. For the non-insulators, the Fermi energy from NSCF calculations is quite bad. Actually, I thought to implement a feature so that the users can provide the Fermi level by themselves (more specifically, use the Fermi energy from SCF calculations). The function "get_band_structure" in pymatgen can accept the Fermi energy input by users. But it looks that it has been on your to do list?
In recent days, when I used sumo to plot band structure, I usually updated the Fermi energy in vasprun.xml first by 'sed' command. It should be easier to use if this feature can be built in sumo.
Thanks very much!

**Comment by ajjackson** [comment]
In line with the discussion, I have made some changes that add a `--zero-line` option plotting a line at the energy zero. The implementation of this line is shared with phonon-dosplot and uses the style information in the same way.

I have removed the comments re: SIGMA shifting and added that to the CHANGELOG

This seems functional to me already as far as drawing lines is concerned. What remains to be done is to provide a _separate_ option setting the energy zero to E_Fermi instead of the VBM. This should make its way to _dos.py_ where the DOS scale is adjusted. I'm having trouble finding where the band structure gets shifted to the VBM - maybe that logic is in Pymatgen? I do find the naming of their `zero_to_efermi` option to be a bit confusing; I tried to clarify in a docstring but may that isn't quite right either.

(Apologies for making somewhat drastic changes on your branch, but this seems the best way of making sure you get credit for your contributions in the Git history!)

**Comment by yw-fang** [comment]
Hi, Adam, no worries, I do like your commits and revisions to my branch! 
I will also take a close look at `zero_to_efermi` option and then get back to you. Thanks very much!

**Comment by yw-fang** [comment]
@ajjackson  I thought the zero you mentioned should refer to the ones in the function of draw_themed_line, thus I fixed it. It works properly on my side.

**Comment by ajjackson** [comment]
I've done the messy merge with master and had a play with the sample files. Things seem to mostly behave as expected: `--zero-line` draws a line at zero when using *bandplot* or *dosplot*. Band structures with included DOS look pretty good with the corrected DOS edge. (i.e. the misleading shift by SIGMA has been removed).
band

A couple of outstanding concerns:
- There still isn't a `--no-shift` or `--fermi-energy` option for *bandplot* that might be used in conjunction with this `--zero-line` feature to draw a line at the Fermi energy.
- Spilling density over the line is going to confuse people when it's a standalone DOS plot. It's the right behaviour, though. Maybe this should be highlighted in documentation?

I propose then we add a `--ref-energy` / `--fermi-energy` option to *bandplot* that accepts either a floating-point number or a calculation file as input. Numbers will uncritically be subtracted from the y-scale so custom shifts are possible. Calculation files compatible with *dosplot* would be checked for a (presumably self-consistent) Fermi energy.

I don't see a practical way to discourage people from providing inappropriate reference files, except through documentation :disappointed: .

**Comment by ajjackson** [comment]
A useful simplification: as we don't really encourage using the Fermi energy directly from the SCF, let's not implement the tricky logic of reading this from a file. Users can get the number themselves, which will encourage thinking about whether the source is appropriate. And then we only need to support one data type :grin:

**Comment by ajjackson** [comment]
Ok, I think the basic functionality is there for shifting zero around.

This should replace the `--no-shift` option so I propose to add a deprecation warning and recommend that users specify `--zero-energy=0.` instead, which is equivalent.

There are various `zero_to_efermi` arguments passed around all over the place; some of these were already non-functional and I think this makes the rest useless as well. As this is an argument to public functions, we should go through a deprecation/compatibility period?

This would be a good point for someone else to take a look. @utf does this implementation make sense to you? Is the deprecation plan ok? I don't see any other deprecation warnings in Sumo so not sure we have an established process there.

**Comment by ajjackson** [comment]
I wanted to check the interaction with Questaal, which took time as I didn't have a working build to hand.

Questaal band structures seem to be fine. Questaal DOS plots... seem to be broken by another bug. Something is not right in the way the dos file is being read. Clearly this should be fixed, but I don't see why it should hold up this feature which is more requested. So I think this is ready to merge?

**Review by kavanase — APPROVED** [review]
Looks good to me! Thanks for working on this @ajjackson!

**Comment by utf** [comment]
Thanks @ajjackson and @yw-fang

**Pull request merged**
