### PR TITLE
Fix missing floating point on y-axis of optplots.

### PR DESCRIPTION
**Pull request by antisymmetric**
In sumo-optplot default behavior rounded y-axis to an apparent float value. 
image.

Format string changed from 'g' to 'f' to allow floating point.

### CODE REVIEW

**Comment by utf** [comment]
Hey Zongda, any update on this?

**Comment by antisymmetric** [comment]
Hi it's Ethan,

Sorry did not notice this before. Tried it and it seems to be working
roughly fine, except that the exponents break for negative numbers.

[image: image.png]

**Comment by utf** [comment]
Whoops, thanks Ethan. Can you try uploading the image via the GitHub page rather than email. The attachment doesn't show.

**Comment by ajjackson** [comment]
ymax=3e4 is fine. I do notice however that we are using the letter "x" for our multiplication rather than the latex `$\times$`. Is there a reason for this? The current behaviour looks pretty bad in some fonts.

absorption

**Comment by ajjackson** [comment]
@utf do you have a strong opinion on x vs `$\times$`? Otherwise I'll change that and merge this.

**Comment by utf** [comment]
Are you able to test whether `$\times$` renders properly using Whitney? I think this would be the only reason to keep `x`.

**Comment by ajjackson** [comment]
I did some font magic. My default behaviour is now this, a free font called Catamaran (
https://fonts.google.com/specimen/Catamaran available at https://github.com/google/fonts/tree/master/ofl/catamaran:
absorption-cat
And it is using proper multiplication symbols, as supported in many fonts including:
absorption-cs

If you have Whitney Extended this will still take preference over other fonts. There is a workaround to replace the \times with a letter 'x' in these fonts.

**Pull request merged**
