### PR TITLE
Add check to skip parsing of break lines in castep band structure k point paths.

### LINKED ISSUE #200: Castep band structure path analyser cannot parse 'break' keyword
In castep the 'break' keyword can be used to specify a jump from one point in k space to another when providing a band structure path. This causes an error in the sumo special k point label finder as the line structure cannot be separated into a tuple of k space coordinates. A simple workaround would be to check if a line in the k point path contains 'break' and ignore such lines.

### PR DESCRIPTION
**Pull request by azanre**
Closes #200 .

### CODE REVIEW

**Comment by ajjackson** [comment]
Thanks for this. I'm struggling to find documentation of this feature; it is mentioned in this old docs archive:

https://www.tcm.phy.cam.ac.uk/castep/documentation/WebHelp/content/modules/castep/keywords/k_bs_kpoint_path_castep.htm

but not in the current docs https://www.tcm.phy.cam.ac.uk/castep/documentation/WebHelp/content/modules/castep/keywords/k_bs_kpoint_path_castep.htm

or in the built-in `castep -h bs_kpoint_path`. So there is little surprise it was overlooked!

Do you have a small sample file that could be used to check this is working as expected, and included in the test suite?

**Comment by azanre** [comment]
It's also mentioned in the castep-docs repo, but definitely not easy to find! https://github.com/castep-docs/castep-docs/blob/develop/docs/documentation/Input_Files/cell_file.md
I'll add an example .cell file and write a unit test for it as well

**Comment by azanre** [comment]
Unit test added - let me know if any more changes are needed

**Comment by ajjackson** [comment]
Looks good to me

**Pull request merged**
