### PR TITLE
Use Matplotlib style sheets

### PR DESCRIPTION
**Pull request by ajjackson**
I have been working on replacing most of the "pretty plot" styling machinery with matplotlib styles, as raised in #13 . So far just the DOS plot is implemented, other stuff is probably broken.

It seems that the best place to apply this style is at the top level, using a style context in the command line programs. The benefit of this is that it reduces the number of "surprises" when working with the Python API and can be set in one place. The flip-side is that the lower-level tools will no longer default to Sumo appearance and a style does need to be set. I've also added a flag to drop the sumo default style; this could be useful if trying to build a style from the ground up or match an existing style. The priority therefore is
```
[userstyle1 > userstyle2 > userstyle3 ...] > [sumo-plot-specific > sumo-base]
```

I think I have a decent resolution to the conflict between the band plot colour scheme and dos plot colour scheme: instead of creating a hybrid scheme, we have the dos plot scheme in the base style, and override it with a two-colour sequence in the band-plot style file. This way any user style sheets can supercede our defaults, and will use the first two colours as expected.

(WIP means "work in progress", please do not merge until it has been removed.)

### CODE REVIEW

**Comment by ajjackson** [comment]
There are now some very minor changes from existing behaviour, i.e. harmonisation of line widths. There's also a bit of magic so that grids always appear on top of data, and bandplot lines stack predictably. This combination makes for some really nice interactions with existing matplotlib styles, e.g. this spin-split bandstructure generated with `sumo-bandplot --style ggplot --no-base-style`

band

**Comment by ajjackson** [comment]
At the moment we have phonon band structure grids still appearing behind the data:
phonon_band

I'm not so wild about the effect of gridlines at the front when the data is more busy
phonon_band

Conceptually a grid is just a visual guide and subservient to the data it sits behind. But in band structures it makes sense to have hard vertical boundaries between the special points, as these values represent direction changes.

**Comment by ajjackson** [comment]
I'm fairly happy with this now. The main remaining niggle is that something has changed about how resizing works and the aspect ratios are getting locked somehow.

**Comment by ajjackson** [comment]
Ok, that's fixed. I think this is good to go?

**Comment by utf** [comment]
@ajjackson This all looks excellent, really nice stuff.

In general the new and old behaviour is pretty identical with some nice tweaks to increase the consistency across plots.

One thing I'm not a fan of is that now the python API does not produce sumo-style plots without first setting the correct series of style sheets. If people are using the sumo API for plotting I think we can assume that they want the sumo style sheet by default, so this introduces a bit of boilerplate for every script.

How difficult would it be to refactor the application of the style sheet to within the plotting functions themselves? I'm imagining the behaviour would be the same just the plot function will now take an additional argument for the style sheet. Would that work?

I'm happy to do this myself btw.

**Comment by ajjackson** [comment]
The technical limitation we're working with is that it's easy to inspect and modify the current styling state, but I don't think it's possible to determine where it has come from.

It's not difficult to move that style logic inside the plot function, but it would become more difficult for users to work with their own styles. For example, they would have no way to set some specific aspects using rcParams before calling the function; they would _have_ to make a special style file if that was the only way we gave them to override Sumo's preferences.

It also adds redundancy as there are multiple different plotter calls within a single style context at the moment. We would have to add the styling logic to each plotter (although I guess some of it can be generalised into a function). Putting the whole plot function in a context block is also a bit ugly; may be best dealt with by having e.g.
```python
SBSPlotter.get_plot(..., style=None, ...)
```
which is a thin wrapper that sets up styling and then calls
```python
SBSPlotter.get_unstyled_plot(...)
```
Users looking to drop the default styling could do their own thing and call `get_unstyled_plot` in that case.

If we're putting this much thought into things we should also consider how users might combine their stuff with base styles. The trouble with the "boilerplate" situation at the moment is that it isn't very easy for the user to find the base style files. We could be cheeky and modify the MPLCONFIGDIR variable. More responsible perhaps would be to assign the file paths to module-level variables, so it becomes

```python
from sumo.plotting import sumo_base_style, sumo_bs_style
with pyplot.style.context([sumo_base_style, sumo_bs_style]):
    rcParams['font.sans-serif'] = 'Comic Sans'
    plotter = SBSPlotter(bs)
    plt = plotter.get_plot()
```

**Comment by utf** [comment]
I've been thinking about what you say here:

> It's not difficult to move that style logic inside the plot function, but it would become more difficult for users to work with their own styles. For example, they would have no way to set some specific aspects using rcParams before calling the function; they would have to make a special style file if that was the only way we gave them to override Sumo's preferences.

Matplotlib allows you to set styles as just a dictionary of values that get passed to rcParams. I've just done a bit of testing and this works nicely. For example, this currently works:

```
base_style = [resource_filename('sumo.plotting', 'sumo_base.mplstyle')]
style = [{'font.size' : 1}]

with matplotlib.pyplot.style.context(base_style + style):
    plotter = SDOSPlotter(dos, pdos)
    plt = plotter.get_plot()
```

If the style sheet code was moved to the plotting functions then this would be possible:

```
style = {'font.size': '1'}

plotter = SDOSPlotter(dos, pdos)
plt = plotter.get_plot(style=style)
```

This should allow users to very easily customise plots.

**Comment by ajjackson** [comment]
This looks exciting! As discussed, we should explicitly refer to `style` and `no_base_style` in the `wrapper` definition.

I'm not sure about the list casting here in plotting/__init__.py:
```python
    def decorator(get_plot):

        def wrapper(*args, **kwargs):

            if 'no_base_style' in kwargs and kwargs['no_base_style']:
                style = []
            else:
                style = list(style_sheets)
```
This will convert a dict to a list of keys and a str to a list of characters.
We should make this docstring a lot more helpful: it should mandate the existence of `style` and `no_base_style` arguments in the decorated function, and be clear that the `*style_sheets` option is a list of _base_ style sheets that will be ignored if `no_base_style`.

**Comment by utf** [comment]
I'll add in `style` and `no_base_style` to the wrapper definition. This will have the benefit plotting functions without these optional arguments can be decorated.

The casting to list should be always be fine as `style_sheets` will always be a tuple.

**Comment by utf** [comment]
I've done some further cleanup of the plotting scripts, like removing some leftover junk and standardising the style across all plots (meaning the stylesheets are slightly cleaner).

I've also added, the following to all of the plots.

```python
ax.xaxis.set_minor_locator(AutoMinorLocator(2))
ax.yaxis.set_minor_locator(AutoMinorLocator(2))
```

The base style sheet now contains:
```
xtick.minor.size     : 0 
ytick.minor.size     : 0 
```
meaning the minor ticks won't be displayed by default but this gives the option of making them visible if users wish to.

I think all that is left is to add a tutorial on how the styling works and how to apply custom styling the via the command line and API.

**Comment by utf** [comment]
Cannot use matplotlib style contexts currently due to a bug in matplotlib.

See https://github.com/matplotlib/matplotlib/issues/11673.

Will re-implement when this issue is resolved.

**Comment by ajjackson** [comment]
I don't think MPL are going to fix this for us soon, and the internals of MPL scare me too much to attempt a pull request.

As this problem only arises when a user a) uses the python API and b) passes an existing axes object (which is admittedly a good use case for the Python API) I think we can live with this.
Let's
* Create module-level variables for the sumo stylesheets e.g. `sumo.plotting.sumo_base_style`
* Keep the `style` and `no_base_style` options in the plotting functions; they are still useful in something like a notebook where we might make repeated calls that produce their own axes
* Use a context at the top level with `no_base_style` in the plot calls for the main CLI plotting
* Add logic to the decorator: if it detects that `ax` and `style` are both used, then print a warning 
  > Using "ax" and "style" arguments: fonts may not be correctly applied to an existing axes object, consider applying styles when creating the axes.

**Comment by ajjackson** [comment]
Reluctantly I'm going along with `matplotlib.style.use`. As implemented currently, matplotlib style contexts don't seem to work well when used inside plotter functions. If someone wants to use contexts with Sumo they can; but they need to use `--no-base-style` when calling plotters to prevent them from messing with the global style.

Have moved the font argument logic to the decorator, it should work properly again now.

**Pull request merged**
