### PR TITLE
Castep support

### PR DESCRIPTION
**Pull request by ajjackson**
Some basic support for CASTEP would be handy.

## For this PR (reading from text files)
- [x] Read band structure from *seedname.bands* file
- [x] Read TDOS from *seedname.bands* file
- [x] Setup band structure with kgen
- [x] Phonon band structure from *seedname.phonon* file

## Future work (involving optados and/or binary files)
- Optics
- PDOS
- Orbital projected bands

### CODE REVIEW

**Comment by ajjackson** [comment]
Like the VASP interface, the user needs to label the high-symmetry points in the place they are specified _(seedname.cell)._ Unlike VASP and Questaal, the kpoint path is not in a separate file, but combined with structural information in the _seedname.cell_ file. What then should `sumo-kgen` do? By analogy with the VASP calculator, we can write a cell file _seedname.cell_bands_ which the user has to rename, or write a _seedname.cell_ in a new directory if `-f` is used. The overall workflow is then quite similar.

**Comment by ajjackson** [comment]
NB commit d76256 makes a good start on implementing kgen but is pretty broken at this point

**Comment by ajjackson** [comment]
kgen seems to work now! With `-f` it will copy a modified .param file (set to _Task : Bandstructure_) and .cell file with the original seednames into new _split-0x_ folders. Without `-f` it writes to cell file(s) in the local directory with a new seedname.

**Comment by ajjackson** [comment]
It turns out that generating a PDOS with CASTEP is a multi-step process; this functionality is performed by the [optados](http://www.tcm.phy.cam.ac.uk/~ajm255/optados/index.html) code which has a very snazzy adaptive broadening capability. There are a couple of options here:

- Have the user run optados and get sumo to generate nice plots from the output (i.e. add an optados interface to Sumo and have the Castep dosplot be DOS-only from the bands output; leads to an increasing number of Sumo interfaces with incomplete feature sets.)
- Have sumo check for the availability of optados, generate an optados input file, call optados and generate a nice plot (more convenient, but could get in the way of people who _want_ to play with optados and still get a Sumo figure at the end.)

**Comment by utf** [comment]
It would be really nice if sumo could generate optados files. If you end up writing an interface for castep, I'd be happy to write the corresponding interface for VASP calculations.

I also think this will make @mkhorton very happy.

**Comment by ajjackson** [comment]
Ok, then we should make the optados interface somewhat decoupled from the Castep one. What kinds of optados bin files have you guys been writing? Do you have a Vasp OPTICS -> _seedname.ome_bin_ converter?

**Comment by utf** [comment]
We aren't actually using optados yet but it is something we are interested in using. I've not actually seen what is necessary for the optados input. I'll have a quick look.

**Comment by mkhorton** [comment]
@utf you know me well 😄

@ajjackson yes, I’ve only ever used it with CASTEP. My understanding is that it’d be fairly straight forward to adapt a VASP LOPTICS run however. Definitely something we’re interested in. 

I don’t know if it affects any plans, but I do have an intent to start adding some CASTEP I/O to pymatgen in the summer after its public release. I’m on a (slow) mission to treat CASTEP as a first class citizen alongside VASP. This is not for any specific project but just because it seems like it’d be healthy for us to have deeper support for another DFT code and it’s something I’d really like to see.

**Comment by ajjackson** [comment]
I've been poking at the CASTEP-ASE interface lately, so we should probably arrange a chat about that! From working on Sumo I can say that Pymatgen's data structures clearly are supposed to support a wide range of codes, but the Vasp focus does occasionally reveal itself (e.g. orbital decomposition only goes up to f) I think it would be a good project for the long-term health of Pymatgen.

Unfortunately while the text files are pretty reasonable the closest thing CASTEP has to vasprun.xml is a binary file. I should have some opportunities soon to ask the developers about that.

**Comment by mkhorton** [comment]
Yes, sounds good!

Agreed re pymatgen's health and our VASP bias. There have been long grumblings that our electronic structure classes could be improved too.

And yes, I'd be interested to hear about that. My concern with CASTEP's ASCII output is that (if I remember rightly) there's a verbosity flag that can radically change what information is printed, I'm not sure how much that will complicate the parser. I have no idea about its binary output. If they could be persuaded to use JSON I think we'd all die happy :D

**Comment by ajjackson** [comment]
My colleague @rebeccafair is working on another Python project that does actually read from the castep_bin, so there is hope. I do wonder if a `castep2dict` library on PyPI would make everyone's lives easier...

**Comment by ajjackson** [comment]
I am leaning towards implementing TDOS and phonon support, which involve reading text files, and leaving orbital-projection and optics for a separate effort as these involve reading binary files or calling optados. I will update the checklist in the top post accordingly: for the record the original checklist was

- Easy stuff
  -  Read band structure from seedname.bands file
  -  Setup band structure with kgen
  -  Read (P)DOS output
- Stretch goals
  - Optics
  - Phonon band structure (Castep has inbuilt Phonon support so this would probably not involve phonopy)
  - Orbital projected bands

**Comment by ajjackson** [comment]
As we will not be interpolating the phonon band structure with Phonopy, it might be helpful to allow the use of kgen to generate appropriate CASTEP input?

**Comment by ajjackson** [comment]
Had a go at integrating CASTEP readers into dosplot and bandplot. Seems to basically work?

I invented some logic to keep information about unsupported arguments in `sumo.io.castep` instead of in _dosplot_. Could do something similar for orbital projection options in _bandplot_?

Need to take a closer look at those .cell file regexes and make sure they cover the `bs_kpoint_path`/`bs_kpoints_path` aliases.

Would also be nice to make a tutorial with a suggested workflow for Castep bands/DOS. i.e.
- self-consistent optimisation with tolerable number of k-points
- reuse the check file for a spectral calculation with dense post-SCF kpoint mesh to get DOS .bands file
- use _kgen_ to setup a band structure calculation
- reuse the check file and perform said bandstructure calculation
- point _bandplot_ at both the BS and DOS _.bands_ files, with a bit of Gaussian smearing on the DOS.
- eyeball the combined plot to decide if the DOS needs more k-points
- obtain a separate DOS using _dosplot_?

**Comment by ajjackson** [comment]
The DOS and band structure now look to be aligned correctly; rather than use alignment logic from the DOS plotter as for Vasp, we just read bs.efermi and use that to shift the DOS energies. It seems a lot safer and more general to do it this way, so maybe that should be rolled out for all codes when doing combined DOS/bands?

**Comment by ajjackson** [comment]
Phonon band structures are working nicely now. A *seedname.phonon* file is recognised as input to *sumo-phonon-bandplot*, which will look for symmetry labels in a *seedname.cell* is possible and plot the band structure.

There's nothing done for the phonon DOS for now; in principle we could read in another *.phonon file for that but I might wait until users are asking for that specifically...

I also rolled in another new feature that could have been a separate PR but made sense as part of checking the correctness of the eigenvalue reader: a `--to-web` option which calls Pymatgen to write a JSON file for use with http://henriquemiranda.github.io/phononwebsite/ . This site allows interactive exploration of the phonon displacements associated with the dispersion plot. As far as I know there is no other converter available for using this tool with CASTEP phonons, so that should be very useful.

**Comment by ajjackson** [comment]
I think this is pretty ready to go, once I've added a few more tests. @mkhorton would you be interested in reviewing?

**Comment by ajjackson** [comment]
I am writing a brief tutorial aimed at novice CASTEP users, and in the process have identified a few small issues:

Actions for this PR:
- [ ] Fermi level / VBM alignment needs fixing for dosplot
- [ ] Consider changing BS_KPOINT... tags to SPECTRAL_KPOINT tags and TASK logic to prefer TASK=SPECTRAL, SPECTRAL_TASK=BANDSTRUCTURE. The Castep devs may deprecate the older redundant syntax.

More general work for other PRs:
- `--no-legend` should probably be on by default for total-DOS-only calculations
- `--no-legend` should exist for combined DOS/band structure plots with *bandplot*. That 'total DOS' is eating a _lot_ of space on the canvas.

**Comment by mkhorton** [comment]
@ajjackson as far as I can tell from reading the diff this looks great! Haven't had a chance to try it interactively yet.

> Consider changing BS_KPOINT... tags to SPECTRAL_KPOINT tags and TASK logic to prefer TASK=SPECTRAL, SPECTRAL_TASK=BANDSTRUCTURE. The Castep devs may deprecate the older redundant syntax.

Coming back to CASTEP myself after a break, I was wondering about this syntax myself. Seems a little confusing. Likewise, why there are multiple `kpoint_path` keywords for e.g. bs, phonon, etc. when to me it seems like a k-point path is a k-point path is a k-point path ...

Also, a question, why is the "hybrid mode" not enabled for CASTEP?

**Comment by ajjackson** [comment]
> I was wondering about this syntax myself. Seems a little confusing. Likewise, why there are multiple kpoint_path keywords for e.g. bs, phonon, etc. when to me it seems like a k-point path is a k-point path is a k-point path ...

This is actually something I really like about Castep, but it is a bit odd coming to it from other codes. There are four kinds of reciprocal-space sampling as far as I know:

1. Electronic k-points used for SCF convergence e.g. KPOINT_MP_GRID
2. Electronic k-points sampled non-self-consistently for single-particle properties after SCF convergence. e.g. SPECTRAL_KPOINT_MP_GRID (which you probably want for a DOS) and SPECTRAL_KPOINT_PATH (which you might use for a band structure). The BS_KPOINT... tags (used with `TASK=BandStructure`) are a legacy alternative to SPECTRAL_KPOINT... (used with `TASK=Spectral`, `SPECTRAL_TASK=BandStructure`) but they are conceptually (and implementation-wise) the same. If the "BS" notation is phased out this becomes less confusing: post-SCF electronic k-points are always "spectral"; you only get to choose one set of them; that set might be used for multiple properties (e.g. optics).
3. Phonon wavevectors sampled to build a force constants model of a harmonic system. This determines either your DFPT wavevectors or a finite supercell. I prefer these to be notated as "_**q**_-points", but in CASTEP they are accessed with PHONON_KPOINT... tags. (Actually in my current field of inelastic neutron scattering it is _less_ confusing this way as we use _**q**_ for _differences_ in wavevector, but I haven't really adjusted yet.) This set of wavevectors determines at which point your phonon frequencies are exact. You _can_ do a band structure this way by performing DFPT at every point, but it's rather costly.
4. Phonon wavevectors sampled by interpolation of the force constants model, accessed with PHONON_FINE_KPOINT... tags. This data is typically used for dense DOS and band structure plotting.

So there is an analogy between BZ sampling for electronic and phonon properties, with  "accurate" and "fast" levels, but the mechanics are different. The MP_GRID/PATH/LIST/DENSITY options are pretty consistent across them. One might propose to rename e.g. KPOINT_MP_GRID to SCF_KPOINT_MP_GRID for further clarity but I doubt this will be well-received!

> Also, a question, why is the "hybrid mode" not enabled for CASTEP?

I have the impression that it is unnecessary in CASTEP, because it properly accounts for the two sets of k-points (as above) without the zero-weighting shenanigans used in VASP. I haven't actually tried out a hybrid DFT band structure yet, though!

**Comment by mkhorton** [comment]
That's a very lucid explanation, thank you! Put that way I can see the sense in it.

By the way, (as above) I'm still looking at adding some basic CASTEP functionality to pymatgen to give something analogous to pymatgen.io.vasp.sets. It might unfortunately require some duplication of effort/functionality, since I'll need to write it in such a way that the API is similar to our VASP capability, but I'm open to suggestions if you have any. In an ideal world, I'd import just `sumo` as a dependency given the nice implementation here.

**Comment by ajjackson** [comment]
Given that Sumo uses Pymatgen as a dependency, I'd be happy if we ended up moving the functionality into Pymatgen and calling it from Sumo. The consistency would help make things a bit tidier and more systematic on this end. I believe Sumo's MIT license would allow you to directly re-use code if that helps?

We would need some kind of transition period, because Sumo's release/breaking-things pace is a bit slower than Pymatgen's ;-)

**Comment by mkhorton** [comment]
> I believe Sumo's MIT license would allow you to directly re-use code if that helps?

That's fair, I understand the license allows for it but politeness may not. If you're fine with that though, then that would be great. I would love to see a `pymatgen.io.castep` module and the `io.castep` here looks like a great starting point. The other thing we've considered is a plug-in system, but I'm not sure how that would work logistically.

The one practical change I'm looking at in pymatgen is to see if we can create a common core Kpoints class that could be used between different electronic structure codes, one reason for this is that we now have several methods to create both uniform k-point grids (e.g. Mueller's method, Gus Hart's, etc.) and several methods to create the lines for line mode (e.g. SeeK, Curtarolo, we have our own scheme now too), and it'd be good to be able to have a common interface to those.

> We would need some kind of transition period, because Sumo's release/breaking-things pace is a bit slower than Pymatgen's ;-)

Point taken :)

**Comment by ajjackson** [comment]
> > I believe Sumo's MIT license would allow you to directly re-use code if that helps?
>
> That's fair, I understand the license allows for it but politeness may not.

Indeed, it is good to discuss these things!

> The one practical change I'm looking at in pymatgen is to see if we can create a common core Kpoints class that could be used between different electronic structure codes

You may find something useful in `sumo.symmetry` where we have an object-oriented setup for working with k-point paths.

**Comment by mkhorton** [comment]
Thanks I'll take a look!

**Comment by ajjackson** [comment]
The tutorial could use some refinement, but should now be a pretty functional tour of the features: https://github.com/ajjackson/castep-sumo-tutorial/blob/master/castep-sumo.org

The hope is to have it hosted/collected with the other CASTEP tutorials for external tools (e.g. Optados, AIRSS, ...) so it is discoverable for CASTEP users without cluttering the main Sumo docs.

**Comment by ajjackson** [comment]
Tests are passing, adjusted objectives have been hit and Codacy doesn't understand assignment from an unpacked tuple. Test coverage is far from complete, but is at least above-average for this project.

I think this is ready to merge once we have received a successful report from a Castep user. I will/have also invited some STFC people to give it a try, so don't feel pressurised @mkhorton :wink:

**Comment by ajjackson** [comment]
Will merge this early next week if nobody objects.

**Comment by utf** [comment]
@ajjackson This is looking fantastic.

I see you've added some additional docs on `sumo-kgen`. It might be nice to have a small section on the castep inputs needed for the other cli tools too.

**Comment by ajjackson** [comment]
The approach here is to assume that the user is using VASP and then add some notes explaining the differences for other codes. That works ok for people who use multiple codes, but

- won't scale well as support is added for more codes and the pages get longer and longer
- is not helpful for novices who may be beginning with e.g. CASTEP.

To address the latter issue I have separately drafted a Sumo tutorial for novice CASTEP users, to be hosted/distributed with other CASTEP training material. Questaal users are currently out of luck, but hopefully do not include many true DFT novices.

A long-term sustainable approach might consist of

- *Generic* documentation for the CLI tools and API that doesn't assume knowledge of any particular atomistic code. It focuses on features that are common across supported codes, and notes where features are supported/unsupported for some codes.
- A tutorial section with a separate walkthrough of the basic use patterns for *each* code. This is presented as the starting-point for new users.

In this branch I put a table in the README summarising compatibility. Perhaps some similar table(s) could be used to provide a refresher/summary of the required input files for each tool with each supported code? It would be more convenient than digging into the full docs every time.

In Daniele Procida's documentation classification then, we would have
- Tutorials (standalone, one per code)
- How-to guides (summary table + Gallery links to CLI usage guides)
- Reference (auto-generated CLI help pages and Python API docs)
- Explanation (citations to academic explanations of features)

In that structure, the CLI usage guide pages could afford to be a bit more terse, with emphasis on providing "recipes", while the beginner tutorials are slow and friendly.

**Comment by utf** [comment]
That sounds like a very nice plan going forward. I agree that the docs will be unmanageable with 3*code specific documentation on each cli page.

Before the new docs structure is up and running, it might be nice to link to your code CASTEP specific tutorials (once they are online) somewhere in the sumo docs.

Thanks again for adding CASTEP functionality. Happy for this to be merged whenever you want.

**Pull request merged**
