### PR TITLE
Functionality to plot dielectric loss function

### PR DESCRIPTION
**Pull request by keeeto**
## Description of work

This PR adds a functionality to plot the loss function as determined from the dielectric function. It is heavily based on the optical absorption routines and reads in from a `vasprun.xml`

This addresses issue #22.

## To test

* Run `setup.py install` on this branch of `sumo`
* In `tests/data/Cs2SnBr6` run `sumo-loss` and `sumo-loss -a`; check that results are sensible
* Check that docstrings produce sensible documentation for the api

### CODE REVIEW

**Comment by keeeto** [comment]
I have resolved two issues for codacy. I don't see the necessity of addressing the warnings about using type() rather than instance() as we are not checking inherited variables.

**Comment by keeeto** [comment]
It's certainly simpler to implement it as its own function - it could be more maintainable to implement it in `optplot`. Additionally, one could extend the `optplot` function to be a general `dielectric properties` plotting function, covering:
   * Dielectric tensor (real and imaginary)
   * Refractive index
   * Optical conductivity
   * Absorption
   * Loss

However, this would obviously necessitate some re-writing of how it works with the cli. 

I'm happy to work on it either way, but I'll leave it to you and @utf as chief architects and maintainers to make this kind of decision call.

**Comment by utf** [comment]
Thanks for the pull request @keeeto, I hadn't realised it was so easy to calculate the optical loss.

I think it makes sense to integrate this into the optplot script, along with the other properties you mentioned.

On where this should be implemented as separate functions vs. optional arguments: do you think it will be useful to plot multiple properties simultaneously (e.g. Absorption & Loss)?

If this is a valid use case then we should go down the optional argument route. We could make the init method for the dielectric plotter accept any number of the dielectric tensor, refractive index, optical conductivity, absorption and loss (through optional arguments). If none are set then an error would be raised.

The behaviour of the `get_plot` function would then depend on the number of properties passed during initialisation. If only one property was included then get_plot should automatically plot that one without any user input.

I'm not sure how this implementation would work if multiple properties were passed. We could default to plotting one property (in an order of preference, say absorption > loss > dielectric tensor ... etc), with the option to turn on an additional property on a secondary y-axis.

Interested to hear your thoughts on this @ajjackson.

Also, even though the `instanceof` is not essential here, we're trying to only accept pull requests with no codacy issues as it clutters the dashboard.

**Comment by ajjackson** [comment]
That sounds like a great idea to me. From a user perspective it could be "sub-command" interface so they type e.g. `sumo-optplot conductivity` with a common set of keyword arguments.

This is only simpler/better from a development perspective if it makes sense to use the same set of options for all of those spectra. Can you think of any which would need to introduce their own additional options?

**Comment by ajjackson** [comment]
Some fairly major stuff here. I hope @keeeto doesn't mind me working on his fork?
`sumo-optplot` now takes a "mode" argument which specifies an optical property or series of properties (currently only "absorption" or "loss"). If multiple modes are set this gives a vertical stack of subplots and corresponding y-axis limits may also be given. This works in conjunction with the existing features to compare different calculations (multiple input files, indicated with line colours) and anisotropic directions (indicated with line style).

Next up is to implement the remaining optical properties in a more elegant way than providing largely-redundant functions for them all. There is one technical question however, which is how to correctly take the square root of an anisotropic dielectric function to obtain the refractive index? Does anyone know any simple examples we can use to check that this is implemented correctly?

In the present implementation of the loss function -Im(1/eps), we reduce the matrix to a vector of complex x, y, z components and take an element-wise reciprocal. I *believe* it would be better to take the inverse of the full matrix even if the off-axis terms are discarded later, as they can change the resulting diagonal elements when the matrix is inverted. As far as I can tell this only matters when the off-diagonal elements are nonzero.

**Comment by ajjackson** [comment]
Ok, I'm pretty happy with this now! I'd like to get it merged in soon as it will help with some Questaal troubleshooting.

- The optics plotter now takes an (ordered) dictionary containing data otherwise formatted as before, to be plotted as a vertical stack of subplots. Standard keys will trigger appropriate axis ranges and y labels.
- The optplot program allows these to be specified at the command line (defaulting to "absorption" for backwards compatibility). You can use these subplots in combination with multiple input files and anisotropic directions
- Actual matrix maths is now used for inverting and square-rooting the the anisotropic dielectric function so off-axis contributions should be handled correctly. It would be nice to compare with a worked example though as all the physics papers/reports I've seen gloss over this step.
- Supported properties are the dielectric function (real and imaginary parts), complex refractive index (real [RI] and imaginary [extinction coefficient] parts), absorption and the energy-loss function.

**Comment by ajjackson** [comment]
Planning to merge this in the next day or so if nobody objects

**Comment by utf** [comment]
This looks great. Thanks @ajjackson.

**Pull request merged**
