### PR TITLE
Add scissor option to bandplot

### PR DESCRIPTION
**Pull request by mkhorton**
Hi all, I thought a scissor option might be useful. I'm not familiar with the structure of the sumo code but this seemed like a logical place to add it.

### CODE REVIEW

**Comment by utf** [comment]
Looks great. Any reason not to merge?

**Comment by ajjackson** [comment]
Might be worth thinking about the interaction/consistency with that proposal to set an optional Fermi level and/or add a horizontal line.

**Comment by mkhorton** [comment]
This shifts using the pymatgen scissor operator which shifts the conduction band energies and keeps the valence bands fixed. As long as a Fermi level / horizontal line is defined relative to the VBM I think this should be fine.

**Comment by ajjackson** [comment]
Should be pretty safe then

**Pull request merged**
