### PR TITLE
Questaal support

### PR DESCRIPTION
**Pull request by ajjackson**
Discussion of general Questaal support is in Issue #31 

So far, this branch implements reading/writing of init.ext files and they can be used to generate k-point path files.

Access in the CLI is via a `--code=questaal` option which has a default value of `vasp`. The interface should be as consistent as possible, with missing features raising a warning or a NotImplementedError.

### CODE REVIEW

**Comment by ajjackson** [comment]
The present challenge is to deal with different unit systems correctly. Laurie has clarified on the questaal bitbucket that
> If you do --band~mq~... it will interpret the k-points it reads as Crystal coordinates. It converts them to Cartesian coordinates internally, so the k-points in file bnds.ext will appear different.

and
> Cartesian units are 2*pi/alat

So:
- We can always read *bnds.ext* as being in Cartesian coordinates
- If *syml.ext* was written in direct coordinates then the special point positions need to be translated to Cartesian coordinates to match the band data
- If *syml.ext* was written in Cartesian coordinates, we may still need to apply a factor of ALAT?
- If the calculation was performed with Bohr distances, we may need to perform a unit conversion for consistency with our pymatgen lattice.
  - It would be simpler to just *not* convert from Bohr to Angstrom when getting the structure, and let Pymatgen see everything in Bohr.

**Comment by ajjackson** [comment]
This warning from Codacy is not especially constructive:

popen-codacy-warning

I need to call the Questaal preprocessor, a compiled Fortran program distributed with another package. "Don't import subprocess" isn't really a viable alternative. Is there a safer way short of maintaining our own version of the preprocessor? 5 minutes seems optimistic...

**Comment by ajjackson** [comment]
Strange, Travis is getting pymatgen-related errors with Python 3.6 but not Python 3.5
```
    from pymatgen.util.coord import pbc_shortest_vectors
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymatgen/util/coord.py", line 9, in <module>
    from . import coord_cython as cuc
  File "__init__.pxd", line 872, in init pymatgen.util.coord_cython
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```
and
```
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymatgen/util/coord.py", line 210, in pbc_shortest_vectors
    return cuc.pbc_shortest_vectors(lattice, fcoords1, fcoords2, mask,
AttributeError: module 'pymatgen.util.coord_cython' has no attribute 'pbc_shortest_vectors'
```

**Comment by ajjackson** [comment]
It's worth commenting here that this branch uses some code that is only supported in Python 3.5 and above. Python 3.4 complains about the multiple list unpacking in
```
    f.write((' '.join(['{:10.8f}'] * 7)).format(e, *r[:3], *i[:3]))
```
As we've already declared Sumo to be for Python 3.5+ I'm inclined to leave this as-is.

**Comment by ajjackson** [comment]
Some problems noticed in Dosplot:
- can reach call to non-existent function _get_pdos
- extension not detected correctly for dos.ext.gz
- site files don't always have `xpos`, need to support cartesian coordinates

**Comment by ajjackson** [comment]
That was helpful! In the course of fixing Dosplot with odd site files, I also enabled kgen to read the site file and have bandplot read ALAT, scaling any Cartesian coordinates appropriately. Bandplot seems to work more consistently now!

**Comment by ajjackson** [comment]
I've been using this routinely for a bit, other people have tried it out. I think it's not drastically more wobbly than the rest of Sumo so pretty ready to merge in. We have lots of stuff to put in a proper release (bugfixes and optics), might as well include this at the same time.

In particular this PR really establishes how to add more supported codes to Sumo, and I've just changed job to somewhere that uses other codes, so have an incentive to add more 😄

**Comment by utf** [comment]
Thanks again for this Adam. I finally got a chance to look through everything properly and it looks great.

I'm going to merge and will rebuild docs and push a new version to Pypi tonight.

**Pull request merged**
