### PR TITLE
Phonon bandplot: JSON dumping/loading, overlaying plots

### PR DESCRIPTION
**Pull request by ajjackson**
Here's an attempt at #65 

So far we can dump a JSON of the Pymatgen object with `--to-json filename.json`, and select multiple of them to add to the plotting output with `--from-json bands-1.json bands-2.json ...`, . If no FORCE_SETS etc. is chosen but --from-json is set, then instead of looking for FORCE_SETS it will just plot the series of JSON files.

I tweaked the style file so the default green is a little darker and we get a green -> pale-blue sequence of up to four colours.

phonon_band

Todo:

- `--style` seems to be broken?
- Check the x-axis scaling is working correctly with some qha data. (If anyone has some lying around that would be great.)
- `--labels`

### CODE REVIEW

**Comment by ajjackson** [comment]
`--legend` argument added, as `--labels` was already taken for path specification!

phonon_band

**Comment by ajjackson** [comment]
Fixed `--style` in #69 , looks like that's been there for a while.

**Comment by ajjackson** [comment]
With styling and lattice corrections this is now useful for working with the quasi-harmonic approximation!

phonon_band

This is PtO2, a very non isotropic unit cell. (The calculations are from gamma-point DFPT on a single unit cell so please don't take the frequencies too seriously.)

**Comment by ajjackson** [comment]
I do wonder if it would be nice to have some way of setting up larger line colour sequences than the length-5 I have set up. I do think 4 is the maximum that one could really recommend for quantitative purposes, but colourmap sweeps could be a nice effect for some qualitative applications (including QHA studies).

**Comment by ajjackson** [comment]
Just needs a couple of tests and then this is done?

**Comment by ajjackson** [comment]
I've added a basic test for the (previously untested) phonopy loader, but that's pretty much a 
phonopy wrapper anyway. I don't see a straightforward way to improve testing of the JSON functionality as we don't really have a framework at the moment for testing the CLI tools and the JSON stuff is just a few lines of logic in there.

The actual JSON file stuff is handled by Pymatgen; it would be nice to have some kind of 'canary' in case Pymatgen changes the format and breaks compatibility with old son files, but I don't suppose we'd actually be able to do much in response.

I consider this ready to merge, with the caveat that we should consider some kind of high-level testing for all the CLI tools that checks the plots and options.

**Comment by utf** [comment]
Thanks for this Adam. These changes look super useful.

I've just pushed a new version to Pypi.

**Pull request merged**
